### ISSUE TITLE
Error after adding to project

### ISSUE THREAD

**Issue by Bobbykart** [Quintschaf/MapItemPicker#10]
Hi, i am getting the following errors when adding your project as dependency:

MapItemController line 57: Referencing instance method 'removingDuplicates()' on 'Array' requires that 'MapItemImage' conform to 'Hashable'

SearchSheet line 41: Incorrect argument label in call (have 'object:', expected 'subject:')

It is enough to add your package into the project and run the project without using your stuff.

**Comment by jayelevy** [comment]
I'm observing the same problem when adding this package in to a new Xcode project. Interestingly, I'm using it in another project (installed package many months ago) and it compiles with no errors.
Xcode version 15.2
MapItemPicker 1.0.4 (both projects... the one that compiles with no errors and the one that fails on the errors listed in prior post)

**Comment by JannThomas** [comment]
Hi 😊 This should be resolved by #11
