### ISSUE TITLE
Package Resolution Failed

### ISSUE THREAD

**Issue by eturkmenler** [Quintschaf/MapItemPicker#4]
Thank you for making this dependency but getting an error of "Package Resolution Failed" while adding it to the SwiftUI package list.

**Comment by JannThomas** [comment]
Hi there, I just published a new release that lowers the minimum swift tools version. Can you please try if it works with the newest release now? 😊

Otherwise, is there a more precise error description somewhere? I can’t really infer what is going wrong with the one you posted.

**Comment by eturkmenler** [comment]
It works now @JannThomas! Thanks for the fix. Can you confirm if you are seeing a jump in memory but no disposing it upon canceling the view?

**Comment by JannThomas** [comment]
Perfect, thanks for confirming that! 

Yes I can confirm that jump in memory and it not going down. As far as I have investigated, it is not possible to remove the memory footprint the Apple `MKMapView` has, I assume it is some sort of MapKit internal caching. That said it only happens once and does not go up again when you present a second time or view.
